spring:
  application:
    name: xchange_Updated
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    static-locations: classpath:/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/XChange_2
    username: Alfred
    password: alfybooze
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
    timeout: 30m
  mail:
    host: smtp.gmail.com
    port: 465
    username: alfybooze@gmail.com
    password: ovgpwvgtknksijsf
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
server:
  port: 8080
  error:
    include-message: always
  servlet:
    session:
      timeout: 30m
      cookie:
        name: XCHANGE_SESSION
        http-only: true
        secure: true
        same-site: strict
        max-age: 1800

security:
  jwt:
    secret-key: "5367566859703373367639792F423F452848284D6251655468576D5A71347437"
    expiration: 1800000 # 30 minutes in milliseconds
    refresh-token:
      expiration: 86400000  # 24 hours in milliseconds
    token:
      cookie-name: jwt_token
      cookie-path: /

logging:
  level:
    org.springframework.security: DEBUG
    org.thymeleaf: DEBUG
    org.hibernate: INFO
    com.Alfy.xchange_Updated: DEBUG
    org.springframework.session: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/xchange.log
    max-size: 10MB
    max-history: 7

# Custom application properties
app:
  cors:
    allowed-origins: http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
  session:
    tracking-modes: cookie
    persistent: true
    max-inactive-interval: 1800
# ...existing code...
currency:
  api:
    url: https://api.apyhub.com/data/convert/currency/multiple
apy:
  hub:
    token: APY0NAw7H8ZPH7lZfHf8SAXz5sRHesLF1bKn7CBC2USmjLYYDtoKHyRp9gcifUm5nsXdKEOC